try:
    result =23/0
except:
    print('error happend')
finally:
    print('finally here')

print('done')